### ISSUE TITLE
Control B6R-W2ZV-0 Wifi Module

### ISSUE THREAD

**Issue by bproulx05** [tritter/homebridge-mertik-fireplace#1]
**Describe Your Problem:**
I have setup the Homebridge plugin and set the correct IP address to my fireplace WiFi Module B6R-W2ZV-0 of Mertik Maxitrol (details of the module here: https://www.valorfireplaces.com/media/Remote/GV60WIFI-Upgrade-Instructions.pdf)

It now appears in HimeKit as a thermostat but it says "This accessory is not responding"

**Logs:**
[1/9/2023, 7:15:48 PM] [MertikFireplace] Initializing MertikFireplace platform...
[1/9/2023, 7:15:48 PM] Loading 1 accessories...
...
[1/9/2023, 7:15:48 PM] [MertikFireplace] Adding new fireplace: Living room
[Living room@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 5
Setup Payload:
X-HM://0024R77XRNH2K
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**
        {
            "fireplaces": [
                {
                    "name": "Living room",
                    "ip": "10.0.133.246"
                }
            ],
            "platform": "MertikFireplace"
        }

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.8
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 16.16.0
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by tritter** [comment]
Hi @bproulx05 could you enable Debug with -D or inside homebridge settings? And provide me a longer more detailed log?
<img width="1376" alt="Screenshot 2023-01-21 at 08 23 27" src="https://user-images.githubusercontent.com/1229109/213848792-45ae20e7-8a85-4e8b-bcb7-95af757dfd73.png">

**Comment by bproulx05** [comment]
Thank you for looking into it.

Here is the log. (I removed parts not related to this plugin.
[homebridge.log.txt](https://github.com/tritter/homebridge-mertik-fireplace/files/10473055/homebridge.log.txt)

**Comment by tritter** [comment]
@bproulx05 just wanted to let you know that I identified the issue and Im working on a fix!

**Comment by bproulx05** [comment]
That is awesome. Thank you!!

Ben

**Comment by tritter** [comment]
@bproulx05 Ben, could you try v1.4.0?
Thanks!

**Comment by bproulx05** [comment]
Awesome. It now connects and retrieve the temperature!

Thank you very much for following up and implementing a fix! Much appreciated.


Ben

**Comment by tritter** [comment]
No problem, sorry for the delay!
